name: Docker

on:
  workflow_call:
  workflow_dispatch:
  # Prime cache
  schedule:
    - cron: '0 0 * * 1,5'

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      packages: write
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y \
            --no-install-recommends flatpak flatpak-builder \
            dbus-daemon git python3
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y flathub org.flatpak.Builder

      - name: Allow file:// clones with git>=2.38.1
        run: |
          git config --global protocol.file.allow always

      - name: Prepare manifest
        run: |
          cd docker
          rm -rf org.flatpak.Builder/
          git clone --depth=1 --branch master --recursive --single-branch https://github.com/flathub/org.flatpak.Builder.git
          cp -vf flatpak-builder-lint-deps.json org.flatpak.Builder/
          python3 rewrite-manifest.py
          flatpak-builder --show-manifest org.flatpak.Builder/org.flatpak.Builder.json >> org.flatpak.Builder-cache.json

      - name: Cache flatpak build
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.flatpak-builder
          key: fb-${{ matrix.platform }}-${{ hashFiles('docker/org.flatpak.Builder-cache.json') }}

      - name: Build flatpak-builder-lint
        run: |
          if [ "${{ matrix.platform }}" = "amd64" ]; then
            arch="x86_64"
          elif [ "${{ matrix.platform }}" = "arm64" ]; then
            arch="aarch64"
          else
            echo "Unsupported platform: ${{ matrix.platform }}"
            exit 1
          fi
          cd docker/org.flatpak.Builder/
          dbus-run-session flatpak run org.flatpak.Builder \
            --state-dir="$GITHUB_WORKSPACE/.flatpak-builder" \
            --arch="$arch" --verbose --user --force-clean --ccache \
            --install-deps-from=flathub builddir org.flatpak.Builder.json
          rm -rf "builddir/files/lib/debug"

      - name: Build the image
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile
          platforms: linux/${{ matrix.platform }}
          push: false
          provenance: false
          load: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ matrix.platform }}
            ghcr.io/${{ github.repository }}:latest-${{ matrix.platform }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}

      - name: Run a sanity check
        run: |
          cd tests/repo/min_success_metadata/gui-app
          dbus-run-session flatpak run org.flatpak.Builder --verbose --user --force-clean --repo=repo \
            --mirror-screenshots-url=https://dl.flathub.org/media \
            --install-deps-from=flathub --ccache builddir org.flathub.gui.yaml
          mkdir -p builddir/files/share/app-info/media
          ostree commit --repo=repo --canonical-permissions --branch=screenshots/$(uname -m) builddir/files/share/app-info/media
          docker run -v $(pwd):/mnt --rm ghcr.io/${{ github.repository }}:latest-amd64 manifest /mnt/org.flathub.gui.yaml
          docker run -v $(pwd):/mnt --rm ghcr.io/${{ github.repository }}:latest-amd64 repo /mnt/repo

      - name: Push the image
        uses: docker/build-push-action@v6
        if: success() && github.event_name != 'pull_request' && github.event_name != 'schedule'
        with:
          context: docker
          file: docker/Dockerfile
          platforms: linux/${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ matrix.platform }}
            ghcr.io/${{ github.repository }}:latest-${{ matrix.platform }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}

      - name: Login to ghcr.io using Flathub credentials
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request' && github.repository == 'flathub-infra/flatpak-builder-lint' && github.event_name != 'schedule'
        with:
          registry: ghcr.io
          username: ${{ secrets.FLATHUB_ORG_USER }}
          password: ${{ secrets.FLATHUB_ORG_TOKEN }}

      - name: Build and push Docker image to the old location
        uses: docker/build-push-action@v6
        if: success() && github.event_name != 'pull_request' && github.repository == 'flathub-infra/flatpak-builder-lint' && github.event_name != 'schedule'
        with:
          context: docker
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: |
            ghcr.io/flathub/flatpak-builder-lint:${{ github.sha }}-${{ matrix.platform }}
            ghcr.io/flathub/flatpak-builder-lint:latest-${{ matrix.platform }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-manifest:
    if: ${{ github.event_name != 'pull_request' && github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - docker
    permissions:
      packages: write
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create \
            ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64 \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-arm64

          docker manifest push ghcr.io/${{ github.repository }}:${{ github.sha }}

          docker manifest create \
            ghcr.io/${{ github.repository }}:latest \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64 \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-arm64

          docker manifest push ghcr.io/${{ github.repository }}:latest

      - name: Login to ghcr.io using Flathub credentials
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request' && github.repository == 'flathub-infra/flatpak-builder-lint'
        with:
          registry: ghcr.io
          username: ${{ secrets.FLATHUB_ORG_USER }}
          password: ${{ secrets.FLATHUB_ORG_TOKEN }}

      - name: Push manifest to the old location
        if: github.event_name != 'pull_request' && github.repository == 'flathub-infra/flatpak-builder-lint'
        run: |
          docker manifest create \
            ghcr.io/flathub/flatpak-builder-lint:${{ github.sha }} \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-amd64 \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-arm64

          docker manifest push ghcr.io/flathub/flatpak-builder-lint:${{ github.sha }}

          docker manifest create \
            ghcr.io/flathub/flatpak-builder-lint:latest \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-amd64 \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-arm64

          docker manifest push ghcr.io/flathub/flatpak-builder-lint:latest
